name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: |
          touch .env
          echo "SHORTISH_CLOUD_REGISTER_URL=${{secrets.shortish_cloud_register_url}}" >> .env
          echo "SHORTISH_CLOUD_SHLINK_URL=${{secrets.shortish_cloud_shlink_url}}" >> .env
      - run: flutter build web --release --no-sound-null-safety
      - run: |
          cd build/web
          echo "shortish.app" > CNAME
          git init
          # type configurations: your user.email and user.name followed lines 
          # git config --global user.email your_email 
          # git config --global user.name your_name 
          git config --global user.email joseph@hassell.dev
          git config --global user.name poster983
          git status
          # change this remote url for examle your remote url is https://github.com/onatcipli/flutter_web.git then the following:
          git remote add origin https://${{secrets.commit_secret}}@github.com/poster983/shlink_app.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
